django_app/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
# from django_app.views import hello, current_datetime, hours_ahead
# from books import views as books_views
from django_app.views import index
from contact import views as contact_views

#generic views of objects
from django.views.generic.list import ListView
# from books.models import Publisher

# publisher_info = {
#     'queryset': Publisher.objects.all(),
#     'template_name': 'publisher_list_page.html',
#     'template_object_name': 'publisher',
#     #add extra context
#     'extra_context': { 'book_list': Book.objects.all }
# }

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_app.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

	# Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	url(r'^$', index),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^contact-us/$', contact_views.contact),
    # url(r'^hello/$', hello),
    # url(r'^time/$', current_datetime),
    # url(r'^time/plus/(\d{1,2})/$', hours_ahead),
    # url(r'^search-form/$', books_views.search_form),
    # url(r'^search/$', books_views.search),
    
    # url(r'^about/$', TemplateView, { 'template': 'about.html' }),
    # url(r'^about/(\w+)/$', books_views.about_pages),
    # url(r'^publishers/$', ListView.as_view(), publisher_info),   
)

# Customer
urlpatterns += patterns('customer.views', 

    url(r'^customer/login/$', 'login'),
    url(r'^customer/loginPost/$', 'loginPost'),
    url(r'^customer/logout/$', 'logout'),
    url(r'^customer/create/$', 'create'),
)

contact/forms.py
from django import forms

class ContactForm(forms.Form):
	subject = forms.CharField(max_length=100)
	email = forms.EmailField(required=False)
	message = forms.CharField(widget=forms.Textarea)

	def clean_message(self):
		message = self.cleaned_data['message']
		num_words = len(message.split())
		if num_words < 4:
			raise forms.ValidationError("Not enough words!")
		return message

contact/views.py
# from django.core.mail import send_email
from django.http import HttpResponse
from django.shortcuts import render
from contact.forms import ContactForm

def contact(request):
	errors = []
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			data = form.cleaned_data
			# send_email(
			# 	data['subject'],
			# 	data['message'],
			# 	data.get('email', 'noreply@example.com'),
			# 	['siteowner@example.com'],
			# 	)
			return HttpResponseRedirect('/contact-us/thanks')
	else:
		form = ContactForm()
			# initial={'subject': 'I love your site!'}
			
	return render(request, 'contact_form.html', { 'form': form })

contact/templates/contact_form.html
<html>
    <head>
        <title>Contact us</title>
        <style type="text/css">
            ul.errorlist {
                margin: 0;
                padding: 0;
            }
            .errorlist li {
                background-color: red;
                color: white;
                display: block;
                font-size: 10px;
                margin: 0 0 3px;
                padding: 4px 5px;
            }
        </style>
    </head>
    <body>
        <h1>Contact us</h1>

        {% if form.errors %}
            <p style="color: red;">
                Please correct the error{{ form.errors|pluralize }} below.
            </p>
        {% endif %}

        <form action="" method="post">
            <table>
            {{ form.as_table }}
            </table>
            <!-- <div class="field">
                {{ form.subject.errors }}
                <label for="id_subject">Subject:</label>
                {{ form.subject }}
            </div>
            <div class="field">
                {{ form.email.errors }}
                <label for="id_email">Your e-mail address:</label>
                {{ form.email }}
            </div>
            <div class="field">
                {{ form.message.errors }}
                <label for="id_message">Message:</label>
                {{ form.message }}
            </div> -->
            {% csrf_token %}
            <input type="submit" value="Submit">
        </form>
    </body>
</html>